### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Kanahiro/GSI-VTDownloader#4]
Can you please check the vector tiles stuff in master which will come out as 3.14 soon and see if the plugin is still relevant

**Comment by Kanahiro** [comment]
Thank you for reviewing.

I know on QGIS 3.14 vectortiles feature will be implemented and already have tried some APIs.
This plugin focuses on downloading vectortiles as vector layers on QGIS, whereas the 3.14 feature treat vectortiles as nearly background, user cannot be get or save vector data.

So this plugin will be useful even on 3.14, I think.

**Comment by NyakudyaA** [comment]
Approved it thanks
